## STEP 1 - BUILD 

FROM golang:1.23-rc-alpine AS build

WORKDIR /demo

COPY go.mod ./


RUN go mod download


COPY *.go ./

RUN go build -o /godemo


## STEP 2 - DEPLOY

FROM scratch


WORKDIR /

COPY --from=build /godemo /godemo


EXPOSE 8080

ENTRYPOINT ["/godemo"]